### ISSUE TITLE
Add search to mobile version

### ISSUE THREAD

**Issue by w3bdesign** [w3bdesign/laravel-vue#890]

**Comment by dassudip2001** [comment]
can i fix this

**Comment by w3bdesign** [comment]
> can i fix this

Feel free to try and open a pull request

@dassudip2001

**Comment by w3bdesign** [comment]
@dassudip2001 

I am coding this myself now, as I haven't heard from you and I need this implemented ASAP

**Comment by dassudip2001** [comment]
No issues

**Comment by w3bdesign** [comment]
> No issues

Open a PR when you are done

**Comment by w3bdesign** [comment]
@dassudip2001
